### ISSUE TITLE
This cycle occurred because of a configuration option when I use bazel build tensorflow in this project.

### ISSUE THREAD

**Issue by chenwenyan** [alibaba/GPU-scheduler-for-deep-learning#5]
hi, @WencongXiao @ShiruRen  I have an error when i execute this command line:
`bazel build  tensorflow/tools/pip_package:build_pip_package`

The output is:
`ERROR: /usr/src/TensorFlow-with-dynamic-scaling/tensorflow/core/BUILD:3290:1: in cc_library rule //tensorflow/core:core_cpu_lib: cycle in dependency graph:
    //tensorflow/tools/pip_package:build_pip_package
    //tensorflow/python/distribute:combinations
    //tensorflow/python/eager:context
    //tensorflow/python/eager:executor
    //tensorflow/python:pywrap_tensorflow
    //tensorflow/python:pywrap_tensorflow_internal
    //tensorflow/python:pywrap_tensorflow_internal.py
    //tensorflow/python:pywrap_tensorflow_internal_py_wrap
    //tensorflow/python:py_func_lib
    //tensorflow/python:safe_ptr
    //tensorflow/c/eager:c_api
    //tensorflow/core/profiler/lib:profiler_lib
    //tensorflow/core/profiler/internal/cpu:host_tracer
.-> //tensorflow/core:core_cpu_lib
|   //tensorflow/core:core_cpu_impl
|   //tensorflow/contrib/resource_management:gpu_resource_management
|   //tensorflow/contrib/resource_management:gpu_usage_adjustment
|   //tensorflow/core:gpu_runtime
|   //tensorflow/core:gpu_runtime_impl
-- //tensorflow/core:core_cpu_lib

This cycle occurred because of a configuration option
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted
INFO: Elapsed time: 0.612s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
`

It seems that there are cycle calls when building this code, is there any idea for it?
I hope someone can help me to solve this problem.

**Comment by Gold-Sea** [comment]
I met the same problem one month ago. I have modified this file but met some other problems with compiling.

**Comment by chenwenyan** [comment]
Have you compiled successfully now?

**Comment by Gold-Sea** [comment]
> 
> 
> Have you compiled successfully now?

No, I gave it up.

**Comment by chenwenyan** [comment]
I have solved this issue and I create [a new repository](https://github.com/chenwenyan/TensorFlow-with-dynamic-scaling-of-AntMan) in my Github. 
Closing it.

**Comment by ShiruRen** [comment]
Sorry for not getting back to you sooner. Big thank to @chenwenyan for finding this bug. This is definitely an important issue that needs to be fixed.
